### PR TITLE
Issue 8

### LINKED ISSUE #8: Erro 500 ao inserir strings no campo do ticket médio
## Steps to reproduce the issue:
1 - Login with an account from the `seeds.rb`;
2 - Go to the side menu, revenue estimations;
image
3 - Go to a new revenue estimation form;
image
4 - type a string in the "ticket médio" field;
5 - Submit it...
image

## Expected behaviour

 - Do not permit creating revenue estimation with invalid inputs.
 - Allow only number with decimal

### PR DESCRIPTION
**Pull request by jonathanmullerr**
## Correção no cálculo de estimativas de receita

Olá! Esta é minha primeira contribuição para este projeto open source.
Fala pessoal! Primeira contribuição no projeto. Se puder melhorar em algom fico a disposição.

close #8

### Resumo das Alterações

Fiz correções no cálculo das estimativas de receita para resolver um problema em que a entrada de valores como strings resultava em um erro 500. Aqui estão os detalhes das alterações:

#### `app/models/revenue_estimation.rb`

- Alteração na função `calculate_quantity` para lidar com entradas não numéricas.
- Mudança para assegurar que `revenue` e `average_ticket` sejam valores numéricos antes do cálculo.
- O método `valid_numeric_inputs?` verifica se `revenue` e `average_ticket` são numéricos e se `average_ticket` não é zero.

#### `app/views/revenue_estimations/_form.html.erb`

- Mudança no input de mês de número livre para dropdown com todos os meses por extenso. Optei por essa alteação para restrigir o usuário de colocar um número fora do range, alé, de ficar mais intuitivo.
- Adicionei formatação de currency nos campos de valor

image
image

### CODE REVIEW

File: spec/models/revenue_estimation_spec.rb [hunk 1]
```diff
@@ -48,4 +48,34 @@
       end
     end
   end
+
+  describe '#calculate_quantity' do
+    context 'with valid inputs' do
+      it 'calculates quantity based on revenue and average_ticket' do
```
Comment (Pauloparakleto) [inline spec/models/revenue_estimation_spec.rb]: Necessary but not sufficient condition to turn RevenueEstimation model invalid. We do not want RevenueEstimation to be created with invalid params, or nil params. Intead of checking nil, `revenue_estimation.valid?` must be false. It will prevent its creation and the `root_path` will not raise error since `revenue_estimation.quantity` is used on the dasboard.

You might check [numericality of the inputs with Rails helpers](https://guides.rubyonrails.org/active_record_validations.html#numericality).

Another good way to prove this validation is using [Shoulda Matcher gem](https://github.com/thoughtbot/shoulda-matchers/blob/main/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb). It is already set in the project. It will increase your productivity creating tests.

File: spec/models/revenue_estimation_spec.rb [hunk 2]
```diff
@@ -48,4 +48,34 @@
...
+        revenue_estimation = RevenueEstimation.new(revenue: 1000, average_ticket: 50)
+        revenue_estimation.send(:calculate_quantity)
+        expect(revenue_estimation.quantity).to eq(20)
+      end
+    end
+
+    context 'with invalid inputs' do
+      it 'handles when revenue or average_ticket is a string' do
+        revenue_estimation = RevenueEstimation.new(revenue: 'invalid', average_ticket: 'invalid')
+        revenue_estimation.send(:calculate_quantity)
```
Comment (Pauloparakleto) [inline spec/models/revenue_estimation_spec.rb]: `revenue_estimation.valid?` to be false

File: spec/models/revenue_estimation_spec.rb [hunk 3]
```diff
@@ -48,4 +48,34 @@
...
+        expect(revenue_estimation.quantity).to be_nil
+      end
+
+      it 'handles zero average_ticket' do
+        revenue_estimation = RevenueEstimation.new(revenue: 1000, average_ticket: 0)
+        revenue_estimation.send(:calculate_quantity)
+        expect(revenue_estimation.quantity).to be_nil
+      end
+
+      it 'handles zero revenue' do
```
Comment (Pauloparakleto) [inline spec/models/revenue_estimation_spec.rb]: `revenue_estimation.valid?` to be false since we do not want to estimate zero revenue.

File: app/views/revenue_estimations/_form.html.erb [hunk 4]
```diff
@@ -30,12 +30,12 @@
   <div class="form-row">
     <div class="form-group col-6">
       <%= f.label :month, :class => 'control-label' %>
-      <%= f.number_field :month, :class => 'form-control', value: f.object.date&.month %>
+      <%= f.select :month, options_for_select((1..12).map { |m| [I18n.t("date.month_names")[m], m] }, f.object.date&.month), {}, class: 'form-control' %>
```
Comment (Pauloparakleto) [inline app/views/revenue_estimations/_form.html.erb]: I liked it 👏🏻 , in another issue I will default it to the current month. Not necessary for now.

File: app/views/revenue_estimations/_form.html.erb [hunk 5]
```diff
@@ -30,12 +30,12 @@
...
     </div>
 
     <div class="form-group col-6">
       <%= f.label :revenue, :class => 'control-label' %>
-      <%= f.text_field :revenue, :class => 'form-control' %>
+      <%= f.text_field :revenue, value: number_to_currency(f.object.revenue, precision: 2), class: 'form-control' %>
```
Comment (Pauloparakleto) [inline app/views/revenue_estimations/_form.html.erb:38]: 👏🏻

File: app/views/revenue_estimations/_form.html.erb [hunk 6]
```diff
@@ -45,7 +45,7 @@
 
     <div class="form-group col-6">
       <%= f.label :average_ticket, :class => 'control-label' %>
-      <%= f.text_field :average_ticket, :class => 'form-control' %>
+      <%= f.text_field :average_ticket, value: number_to_currency(f.object.average_ticket, precision: 2), class: 'form-control' %>
```
Comment (Pauloparakleto) [inline app/views/revenue_estimations/_form.html.erb:48]: 👏🏻

**Review by Pauloparakleto — COMMENTED** [review]
You did a good job understanding the context. In the model's level, a sufficient condition to prevent a model creation is checking `Model.valid?`. We do not want an invalid model to be created. I did a couple of comments in order to improve your skills.

File: spec/models/revenue_estimation_spec.rb (hunk 1 above)
Comment (jonathanmullerr) [reply spec/models/revenue_estimation_spec.rb]: Great idea! I just adjusted it

File: spec/models/revenue_estimation_spec.rb [hunk 7]
```diff
@@ -19,6 +19,7 @@
     it { is_expected.to validate_presence_of(:revenue) }
     it { is_expected.to validate_presence_of(:date) }
     it { is_expected.to validate_numericality_of(:revenue) }
+    it { is_expected.to validate_numericality_of(:average_ticket).is_greater_than(0) }
```
Comment (Pauloparakleto) [inline spec/models/revenue_estimation_spec.rb:22]: This is indeed a necessary and sufficient condition to prove both when it is invalid by a string and a non-zero input.
Soon you will realize the entire `context "invalid"` can be replaced by just this single line.
For now, please remove the invalid block since it is now redundant against the power of shoulda matcher. Shouldamatcher does all this for us under the hood.

File: spec/models/revenue_estimation_spec.rb [hunk 8]
```diff
@@ -47,5 +48,26 @@
...
+      end
+
+      it 'handles zero average_ticket' do
+        revenue_estimation = build(:revenue_estimation, revenue: 50, average_ticket: 0)
+        expect(revenue_estimation).not_to be_valid
+      end
+    end
+  end
+
+  describe '#calculate_quantity' do
```
Comment (Pauloparakleto) [inline spec/models/revenue_estimation_spec.rb]: It is redundant since it is already calculated in the `context 'valid'`. Check line 35.

**Review by Pauloparakleto — COMMENTED** [review]
Just a few comments

File: spec/models/revenue_estimation_spec.rb (hunk 7 above)
Comment (jonathanmullerr) [reply spec/models/revenue_estimation_spec.rb:22]: Perfect! Just remove the unseless specs.

File: app/views/revenue_estimations/_form.html.erb (hunk 4 above)
Comment (jonathanmullerr) [reply app/views/revenue_estimations/_form.html.erb]: Just did it! Haha

File: spec/models/revenue_estimation_spec.rb [hunk 9]
```diff
@@ -47,5 +48,17 @@
         expect(subject.date.month).to eq(10)
       end
     end
+     
+    context "invalid" do
```
Comment (Pauloparakleto) [inline spec/models/revenue_estimation_spec.rb]: This is also a redundant expectation since you already wrote the shoulda matcher test for it. Check line 22. For your growth.
